version: '2'
services:
    web:
        build: .
        volumes:
            - ./:/var/www/html
            - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf
        ports:
            - '80:80'
        env_file: .env
    redis:
        image: redis
        ports:
            - '6379:6379'
        volumes:
            - ./data/redis:/data
    postgres:
        image: postgres
        ports:
            - '5432:5432'
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=coinbase
            - POSTGRES_PASSWORD=secretrandompassword
            - POSTGRES_DB=coinbase
